name: flutter_delay_fetch
description: A flutter plugin to put a delay between fetch request and parsing data with a mixin, during page route navigation to avoid laggy animations.
version: 1.1.0
repository: https://github.com/jonasroussel/flutter_delay_fetch
homepage: https://github.com/jonasroussel/flutter_delay_fetch#readme

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

